version: '3'

services:
  second-container:
    build:
      context: ./express1
      dockerfile: Dockerfile
    container_name: 'second-container'
    ports:
      - '3001:3001'
    restart: 'no'
    environment:
      - NODE_ENV=production
    networks:
      - my-network
    image: my-registry/my-second-container:latest

  third-container:
    build:
      context: ./express2
      dockerfile: Dockerfile
    container_name: 'third-container'
    ports:
      - '3000:3000'
    restart: 'no'
    environment:
      - NODE_ENV=production
    networks:
      - my-network
    image: my-registry/my-third-container:latest

networks:
  my-network: